Add auth, landing and structure all files
flickzapp/flickz pull request #1
Opened 2023-08-06 14:44 UTC by Ashutosh-Bhadauriya

2023-08-06 18:41 UTC, Ankur-Datta-4 commented on app/(marketing)/page.tsx
> +        <div className="flex flex-col items-center justify-between gap-8">
Since the aim is to keep all the text in the landing page to lower case, I think its good to add a tailwind class: 
`lowercase` here

2023-08-06 18:46 UTC, Ankur-Datta-4 commented on app/(marketing)/page.tsx
> +const stars = 1000;
Lessgo 1000 stars xD

2023-08-06 18:53 UTC, Ankur-Datta-4 commented on app/layout.tsx
> +    <html lang="en" suppressHydrationWarning>
Since we have the logo, we could also add favicon right>?

2023-08-06 18:53 UTC, Ankur-Datta-4 requested changes
Just a couple tweaks away! And then we'll squash commit so that the intermediate env isn't visible!

2023-08-07 03:37 UTC, Ashutosh-Bhadauriya commented
Changes done 👍

2023-08-07 03:47 UTC, Ankur-Datta-4 approved these changes

2023-08-07 03:48 UTC, merged